# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d52d68b142f45789009845211a7a93b6d638a7a7dfec1b2dacc129d1b28ee486887d10be3b27d6110c6289f3fe0796f0f2de0fac17e5ec77b36562208af6f19

test:
  secret_key_base: 267055628ab5d7308434c3186d790cc70a4889f7a9ef3e34df10a5f97702ba0ded896309b4fe8f4255ce9ec67c03eb8a12ee26adbf2eb4f02a887b59a19cc5eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
